export const cow = {
  0: ["...", "..."],
  1: ["Afghanistan", "kabul"],
  2: ["Albania", "tirana"],
  3: ["Algeria", "algiers"],
  4: ["Andorra", "andorra la vella"],
  5: ["Angola", "luanda"],
  6: ["Antigua and Barbuda", "saint john's"],
  7: ["Argentina", "buenos aires"],
  8: ["Armenia", "yerevan"],
  9: ["Australia", "canberra"],
  10: ["Austria", "vienna"],
  11: ["Azerbaijan", "baku"],
  12: ["The Bahamas", "nassau"],
  13: ["Bahrain", "manama"],
  14: ["Bangladesh", "dhaka"],
  15: ["Barbados", "bridgetown"],
  16: ["Belarus", "minsk"],
  17: ["Belgium", "brussels"],
  18: ["Belize", "belmopan"],
  19: ["Benin", "porto-novo"],
  20: ["Bhutan", "thimphu"],
  21: ["Bolivia", "la paz sucre"],
  22: ["Bosnia and Herzegovina", "sarajevo"],
  23: ["Botswana", "gaborone"],
  24: ["Brazil", "brasilia"],
  25: ["Brunei", "bandar seri begawan"],
  26: ["Bulgaria", "sofia"],
  27: ["Burkina Faso", "ouagadougou"],
  28: ["Burundi", "gitega bujumbura"],
  29: ["Cambodia", "phnom penh"],
  30: ["Cameroon", "yaounde"],
  31: ["Canada", "ottawa"],
  32: ["Cape Verde", "praia"],
  33: ["Central African Republic", "bangui"],
  34: ["Chad", "djamena"],
  35: ["Chile", "santiago"],
  36: ["China", "beijing"],
  37: ["Colombia", "bogota"],
  38: ["Comoros", "moroni"],
  39: ["Congo", "brazzaville"],
  40: ["the Democratic Republic of the Congo", "kinshasa"],
  41: ["Costa Rica", "san jose"],
  42: ["Cote d'Ivoire", "yamoussoukro abidjan"],
  43: ["Croatia", "zagreb"],
  44: ["Cuba", "havana"],
  45: ["Cyprus", "nicosia"],
  46: ["Czech Republic", "prague"],
  47: ["Denmark", "copenhagen"],
  48: ["Djibouti", "djibouti"],
  49: ["Dominica", "roseau"],
  50: ["Dominican Republic", "santo domingo"],
  51: ["East Timor (Timor-Leste)", "dili"],
  52: ["Ecuador", "quito"],
  53: ["Egypt", "cairo"],
  54: ["El Salvador", "san salvador"],
  55: ["Equatorial Guinea", "malabo"],
  56: ["Eritrea", "asmara"],
  57: ["Estonia", "tallinn"],
  58: ["Ethiopia", "addis ababa"],
  59: ["Fiji", "suva"],
  60: ["Finland", "helsinki"],
  61: ["France", "paris"],
  62: ["Gabon", "libreville"],
  63: ["The Gambia", "banjul"],
  64: ["Georgia", "tbilisi"],
  65: ["Germany", "berlin"],
  66: ["Ghana", "accra"],
  67: ["Greece", "athens"],
  68: ["Grenada", "saint george's"],
  69: ["Guatemala", "guatemala city"],
  70: ["Guinea", "conakry"],
  71: ["Guinea-Bissau", "bissau"],
  72: ["Guyana", "georgetown"],
  73: ["Haiti", "port-au-prince"],
  74: ["Honduras", "tegucigalpa"],
  75: ["Hungary", "budapest"],
  76: ["Iceland", "reykjavik"],
  77: ["India", "new delhi"],
  78: ["Indonesia", "jakarta"],
  79: ["Iran", "tehran"],
  80: ["Iraq", "baghdad"],
  81: ["Ireland", "dublin"],
  82: ["Israel", "jerusalem*"],
  83: ["Italy", "rome"],
  84: ["Jamaica", "kingston"],
  85: ["Japan", "tokyo"],
  86: ["Jordan", "amman"],
  87: ["Kazakhstan", "nur-sultan"],
  88: ["Kenya", "nairobi"],
  89: ["Kiribati", "tarawa atoll"],
  90: ["Korea, North", "pyongyang"],
  91: ["Korea, South", "seoul"],
  92: ["Kosovo", "pristina"],
  93: ["Kuwait", "kuwait city"],
  94: ["Kyrgyzstan", "bishkek"],
  95: ["Laos", "vientiane"],
  96: ["Latvia", "riga"],
  97: ["Lebanon", "beirut"],
  98: ["Lesotho", "maseru"],
  99: ["Liberia", "monrovia"],
  100: ["Libya", "tripoli"],
  101: ["Liechtenstein", "vaduz"],
  102: ["Lithuania", "vilnius"],
  103: ["Luxembourg", "luxembourg"],
  104: ["Macedonia", "skopje"],
  105: ["Madagascar", "antananarivo"],
  106: ["Malawi", "lilongwe"],
  107: ["Malaysia", "kuala lumpur"],
  108: ["Maldives", "male"],
  109: ["Mali", "bamako"],
  110: ["Malta", "valletta"],
  111: ["Marshall Islands", "majuro"],
  112: ["Mauritania", "nouakchott"],
  113: ["Mauritius", "port louis"],
  114: ["Mexico", "mexico city"],
  115: ["the Federated States of Micronesia", "palikir"],
  116: ["Moldova", "chisinau"],
  117: ["Monaco", "monaco"],
  118: ["Mongolia", "ulaanbaatar"],
  119: ["Montenegro", "podgorica"],
  120: ["Morocco", "rabat"],
  121: ["Mozambique", "maputo"],
  122: ["Myanmar (Burma)", "rangoon naypyidaw nay pyi taw"],
  123: ["Namibia", "windhoek"],
  124: ["Nepal", "kathmandu"],
  125: ["Netherlands", "amsterdam"],
  126: ["New Zealand", "wellington"],
  127: ["Nicaragua", "managua"],
  128: ["Niger", "niamey"],
  129: ["Nigeria", "abuja"],
  130: ["Norway", "oslo"],
  131: ["Oman", "muscat"],
  132: ["Pakistan", "islamabad"],
  133: ["Palau", "melekeok"],
  134: ["Panama", "panama city"],
  135: ["Papua New Guinea", "port moresby"],
  136: ["Paraguay", "asuncion"],
  137: ["Peru", "lima"],
  138: ["Philippines", "manila"],
  139: ["Poland", "warsaw"],
  140: ["Portugal", "lisbon"],
  141: ["Qatar", "doha"],
  142: ["Romania", "bucharest"],
  143: ["Russia", "moscow"],
  144: ["Rwanda", "kigali"],
  145: ["Saint Kitts and Nevis", "basseterre"],
  146: ["Saint Lucia", "castries"],
  147: ["Saint Vincent and the Grenadines", "kingstown"],
  148: ["Samoa", "apia"],
  149: ["San Marino", "san marino"],
  150: ["Sao Tome and Principe", "sao tome"],
  151: ["Saudi Arabia", "riyadh"],
  152: ["Senegal", "dakar"],
  153: ["Serbia", "belgrade"],
  154: ["Seychelles", "victoria"],
  155: ["Sierra Leone", "freetown"],
  156: ["Singapore", "singapore"],
  157: ["Slovakia", "bratislava"],
  158: ["Slovenia", "ljubljana"],
  159: ["Solomon Islands", "honiara"],
  160: ["Somalia", "mogadishu"],
  161: ["South Africa", "pretoria cape town bloemfontein"],
  162: ["South Sudan", "juba"],
  163: ["Spain", "madrid"],
  164: ["Sri Lanka", "colombo sri jayewardenepura kotte"],
  165: ["Sudan", "khartoum"],
  166: ["Suriname", "paramaribo"],
  167: ["Swaziland", "mbabane"],
  168: ["Sweden", "stockholm"],
  169: ["Switzerland", "bern"],
  170: ["Syria", "damascus"],
  171: ["Taiwan", "taipei"],
  172: ["Tajikistan", "dushanbe"],
  173: ["Tanzania", "dar es salaam dodoma"],
  174: ["Thailand", "bangkok"],
  175: ["Togo", "lome"],
  176: ["Tonga", "nuku'alofa"],
  177: ["Trinidad and Tobago", "port-of-spain"],
  178: ["Tunisia", "tunis"],
  179: ["Turkey", "ankara"],
  180: ["Turkmenistan", "ashgabat"],
  181: ["Tuvalu", "vaiaku village funafuti province"],
  182: ["Uganda", "kampala"],
  183: ["Ukraine", "kyiv"],
  184: ["United Arab Emirates", "abu dhabi"],
  185: ["United Kingdom", "london"],
  186: ["United States of America", "washington, d.c. washington"],
  187: ["Uruguay", "montevideo"],
  188: ["Uzbekistan", "tashkent"],
  189: ["Vanuatu", "port-vila"],
  190: ["Vatican City (Holy See)", "vatican city"],
  191: ["Venezuela", "caracas"],
  192: ["Vietnam", "hanoi"],
  193: ["Yemen", "sanaa"],
  194: ["Zambia", "lusaka"],
  195: ["Zimbabwe", "harare"],
};
